// Curated activity library. Every activity is offline-first and screen-free.
// setting: home | outside (yard/street/park nearby) | out (a trip somewhere)
// energy: calm | active   mess: 0 none, 1 some, 2 messy
// weather: any | dry | wet (wet = great for rainy days)

export const CATEGORIES = {
  sensory:    { label: 'Sensory play',  emoji: '🫧' },
  nature:     { label: 'Nature',        emoji: '🌿' },
  lifeskills: { label: 'Life skills',   emoji: '🧺' },
  stem:       { label: 'Curious minds', emoji: '🔬' },
  art:        { label: 'Make & create', emoji: '🎨' },
  movement:   { label: 'Move & play',   emoji: '🤸' },
  together:   { label: 'Connection',    emoji: '💛' },
};

const A = (id, title, emoji, cat, ages, mins, setting, energy, mess, weather, materials, steps, skills, tip = '') =>
  ({ id, title, emoji, cat, ages, mins, setting, energy, mess, weather, materials, steps, skills, tip });

export const ACTIVITIES = [
  // ---------- Sensory ----------
  A('rice-bin', 'Rainbow rice sensory bin', '🌈', 'sensory', [2, 6], 30, 'home', 'calm', 1, 'any',
    ['Uncooked rice', 'Food colouring + a splash of vinegar', 'Zip bags', 'Cups & spoons'],
    ['Shake rice, a few drops of colour and a splash of vinegar in a bag.', 'Spread on a tray to dry (~20 min).', 'Pour into a bin with cups, spoons and small toys to bury and find.'],
    ['Fine motor', 'Colour words', 'Focus'], 'Lay a bed sheet underneath — clean-up becomes one shake outside.'),
  A('ice-rescue', 'Frozen toy rescue', '🧊', 'sensory', [2, 7], 30, 'home', 'calm', 1, 'any',
    ['Small toys', 'Container + freezer', 'Warm water, salt, spoons, droppers'],
    ['The night before, freeze small toys in water.', 'Give kids warm water, salt and tools to "rescue" them.', 'Ask: which tool melts ice fastest?'],
    ['Problem solving', 'Cause & effect', 'Patience']),
  A('mud-kitchen', 'Mud kitchen café', '🥧', 'sensory', [2, 8], 45, 'outside', 'calm', 2, 'dry',
    ['Old pots & spoons', 'Dirt + water', 'Leaves, petals, sticks'],
    ['Set up a "kitchen" on a step or crate.', 'Kids mix mud pies, leaf soups and petal cakes.', 'Take "orders" from grown-ups and pay with leaves.'],
    ['Pretend play', 'Language', 'Counting']),
  A('sound-walk', 'Listening walk', '👂', 'sensory', [2, 10], 20, 'outside', 'calm', 0, 'any',
    ['Nothing! (optional: paper to tally)'],
    ['Walk slowly and stay silent for one minute.', 'Count every different sound you hear.', 'Sort them: nature, people, machines. Which was loudest? Quietest?'],
    ['Attention', 'Mindfulness', 'Vocabulary']),
  A('playdough', 'No-cook playdough', '🟣', 'sensory', [2, 8], 30, 'home', 'calm', 1, 'any',
    ['2 cups flour', '½ cup salt', '1 tbsp oil', '~1 cup warm water', 'Food colouring'],
    ['Mix flour and salt.', 'Add oil, colour and water bit by bit and knead.', 'Make creatures, pretend cookies, or letters of their name.'],
    ['Hand strength', 'Measuring', 'Creativity'], 'Stores for weeks in an airtight bag.'),
  A('texture-hunt', 'Texture treasure hunt', '🪨', 'sensory', [2, 6], 20, 'home', 'calm', 0, 'any',
    ['A bag or basket'],
    ['Call out a texture: smooth, bumpy, soft, scratchy.', 'Kids race to find something that matches.', 'Swap roles — kids call, you hunt.'],
    ['Describing words', 'Sorting']),
  A('water-wall', 'Water pouring station', '💧', 'sensory', [1, 5], 30, 'outside', 'calm', 2, 'dry',
    ['Tubs of water', 'Cups, funnels, jugs, sponges'],
    ['Set out tubs and pouring tools on the grass.', 'Pour, squeeze, fill and empty.', 'Challenge: fill the jug using only the sponge.'],
    ['Fine motor', 'Early maths (full/empty)'], 'Always supervise water play, even shallow tubs.'),

  // ---------- Nature ----------
  A('scavenger', 'Nature scavenger hunt', '🔍', 'nature', [3, 10], 45, 'outside', 'active', 0, 'dry',
    ['A bag', 'The checklist below (or draw one)'],
    ['Find: a Y-shaped stick, 3 different leaves, something soft, a seed, something red.', 'Bonus: a bird sound, a bug (look, don\'t take).', 'Lay finds out at home and sort by colour or size.'],
    ['Observation', 'Classification'], 'Pairs perfectly with any park or trail from Near Me.'),
  A('leaf-rub', 'Leaf rubbings', '🍂', 'nature', [3, 9], 25, 'home', 'calm', 0, 'any',
    ['Leaves', 'Paper', 'Crayons with paper peeled off'],
    ['Collect leaves of different shapes.', 'Place under paper, vein side up.', 'Rub crayon sideways and watch the leaf appear.'],
    ['Observation', 'Fine motor']),
  A('bird-feeder', 'Pinecone bird feeder', '🐦', 'nature', [3, 10], 30, 'home', 'calm', 1, 'any',
    ['Pinecone', 'Seed butter or lard', 'Birdseed', 'String'],
    ['Tie string around the top of the pinecone.', 'Spread with butter, roll in birdseed.', 'Hang outside a window and keep a bird tally for a week.'],
    ['Patience', 'Caring for animals', 'Data collection'], 'Use seed butter to keep it nut-free.'),
  A('cloud-spot', 'Cloud-spotting picnic', '☁️', 'nature', [2, 12], 30, 'outside', 'calm', 0, 'dry',
    ['Blanket', 'Snack'],
    ['Lie back and find shapes in the clouds.', 'Invent a story connecting three cloud shapes.', 'Older kids: look up cumulus vs. cirrus and name today\'s clouds.'],
    ['Imagination', 'Storytelling', 'Weather science']),
  A('bug-hotel', 'Build a bug hotel', '🐞', 'nature', [4, 12], 60, 'outside', 'calm', 1, 'dry',
    ['Old plant pot or tin can', 'Sticks, pinecones, bark, straw'],
    ['Pack the container tightly with natural materials.', 'Place it in a shady, sheltered spot on its side.', 'Check weekly — who moved in?'],
    ['Ecosystems', 'Patience', 'Building']),
  A('puddle-jump', 'Puddle science walk', '🌧️', 'nature', [2, 9], 30, 'outside', 'active', 2, 'wet',
    ['Rain boots & raincoat', 'Stick or ruler'],
    ['Go out in (or right after) the rain.', 'Measure puddle depth with a stick. Predict which is deepest.', 'Jump! Which splash was biggest?'],
    ['Measuring', 'Prediction', 'Joy'], 'Skip if there is thunder or lightning.'),
  A('seed-sprout', 'Sprout a bean in a jar', '🌱', 'nature', [3, 10], 15, 'home', 'calm', 0, 'any',
    ['Clear jar', 'Paper towel', 'Dried beans', 'Water'],
    ['Line a jar with damp paper towel.', 'Tuck 3 beans between towel and glass.', 'Check daily; draw what changes in a little journal.'],
    ['Life cycles', 'Responsibility', 'Recording observations'], 'A great long-term project — 2 weeks of daily check-ins.'),
  A('stargaze', 'Backyard star party', '✨', 'nature', [4, 12], 40, 'outside', 'calm', 0, 'dry',
    ['Blanket', 'Warm drinks', 'Red-tinted torch (optional)'],
    ['Wait until it is properly dark; let eyes adjust 10 min.', 'Find the brightest "star" — it may be a planet.', 'Make up your own family constellation and name it.'],
    ['Astronomy', 'Wonder', 'Patience']),
  A('rock-paint', 'Kindness rocks', '🪨', 'nature', [3, 12], 45, 'home', 'calm', 1, 'any',
    ['Smooth rocks', 'Acrylic paint or markers'],
    ['Collect smooth rocks on a walk.', 'Paint pictures or kind words.', 'Hide them on your next walk for strangers to find.'],
    ['Kindness', 'Creativity', 'Fine motor']),
  A('nature-journal', 'Start a nature journal', '📓', 'nature', [5, 12], 30, 'outside', 'calm', 0, 'any',
    ['Notebook', 'Pencil & crayons'],
    ['Sit in one spot for 10 minutes.', 'Draw one thing closely: a leaf, a bug, a tree.', 'Write the date, weather and one question you wonder about.'],
    ['Observation', 'Writing', 'Curiosity'], 'Return to the same spot each season and compare.'),

  // ---------- Life skills ----------
  A('snack-chef', 'Little chef: make your own snack', '🥪', 'lifeskills', [3, 10], 25, 'home', 'calm', 1, 'any',
    ['Bread or crackers', 'Spreads, sliced fruit', 'Butter knife'],
    ['Wash hands together.', 'Kids spread, layer and cut with a butter knife.', 'They serve the family and help wipe the table.'],
    ['Independence', 'Hygiene', 'Hand-eye coordination']),
  A('laundry-sort', 'Laundry sorting game', '🧦', 'lifeskills', [2, 7], 15, 'home', 'calm', 0, 'any',
    ['A basket of clean laundry'],
    ['Sort by colour, then by owner.', 'Find all sock pairs — race the timer!', 'Older kids fold towels and match socks solo.'],
    ['Sorting', 'Matching', 'Contributing']),
  A('grocery-quest', 'Grocery store quest', '🛒', 'lifeskills', [4, 12], 45, 'out', 'active', 0, 'any',
    ['A short shopping list', 'Small budget in cash (older kids)'],
    ['Give kids their own 3-item list (pictures for non-readers).', 'They find items, compare prices, pick fruit.', 'Older kids pay and check the change.'],
    ['Money', 'Decision making', 'Reading'], 'Weekday mornings are calmest.'),
  A('plant-care', 'Plant care crew', '🪴', 'lifeskills', [3, 10], 15, 'home', 'calm', 1, 'any',
    ['House plants or herbs', 'Small watering can'],
    ['Assign each child one plant to care for.', 'Check soil with a finger: dry = water.', 'Give the plant a name and a weekly check-in day.'],
    ['Responsibility', 'Routine', 'Empathy']),
  A('bake-together', 'Bake muffins together', '🧁', 'lifeskills', [3, 12], 60, 'home', 'calm', 2, 'any',
    ['A simple muffin recipe', 'Measuring cups', 'Bowl & tray'],
    ['Read the recipe together; kids gather ingredients.', 'Kids measure, crack eggs and stir.', 'Grown-ups handle the oven; kids set a timer and clean up.'],
    ['Maths (measuring)', 'Following steps', 'Patience'], 'Grown-ups handle anything hot.'),
  A('tie-shoes', 'Shoe-tying practice', '👟', 'lifeskills', [4, 7], 15, 'home', 'calm', 0, 'any',
    ['A shoe or cardboard with laces'],
    ['Use the "bunny ears" method: two loops, cross, tuck.', 'Practice on a shoe on the table first, not on feet.', 'Celebrate each try, not just success.'],
    ['Fine motor', 'Persistence']),
  A('pack-bag', 'Pack your own adventure bag', '🎒', 'lifeskills', [3, 10], 15, 'home', 'calm', 0, 'any',
    ['Backpack', 'Picture checklist: water, snack, hat, jacket'],
    ['Check today\'s weather together.', 'Kids decide what they need and pack it.', 'At the end of the trip, chat: what did we forget? What did we not need?'],
    ['Planning', 'Independence', 'Reflection']),
  A('mini-garden', 'Plant a windowsill herb garden', '🌿', 'lifeskills', [3, 12], 40, 'home', 'calm', 1, 'any',
    ['Small pots', 'Soil', 'Herb seeds (basil, cress)'],
    ['Fill pots and plant seeds (follow packet depth).', 'Label each pot.', 'Water and harvest into a family meal in a few weeks.'],
    ['Responsibility', 'Life cycles', 'Healthy eating']),
  A('call-family', 'Make a call to grandparents', '☎️', 'lifeskills', [3, 12], 15, 'home', 'calm', 0, 'any',
    ['A phone (used as a telephone!)'],
    ['Kids practise a greeting and 2 questions beforehand.', 'They dial and lead the conversation.', 'Afterwards, draw a picture of something they heard.'],
    ['Communication', 'Connection', 'Confidence']),

  // ---------- STEM / curious minds ----------
  A('volcano', 'Kitchen volcano', '🌋', 'stem', [3, 10], 30, 'home', 'active', 2, 'any',
    ['Baking soda', 'Vinegar', 'Dish soap', 'Food colouring', 'Cup on a tray'],
    ['Put 2 spoons of baking soda in a cup with a squirt of soap.', 'Add colour to vinegar and pour in.', 'Experiment: more soda? warm vinegar? Which erupts biggest?'],
    ['Chemistry', 'Prediction', 'Fair testing']),
  A('sink-float', 'Sink or float?', '🛁', 'stem', [2, 8], 25, 'home', 'calm', 1, 'any',
    ['Tub of water', '10 household objects'],
    ['Kids guess sink or float for each object first.', 'Test one by one and sort into two piles.', 'Can you make a sinker float (e.g. a foil boat)?'],
    ['Hypothesis', 'Density', 'Recording results']),
  A('paper-plane', 'Paper plane test flight', '✈️', 'stem', [5, 12], 40, 'home', 'active', 0, 'any',
    ['Paper', 'Tape measure or steps'],
    ['Fold 3 different plane designs.', 'Fly each 3 times and measure distance.', 'Change one thing (wing fold, paperclip) and test again.'],
    ['Engineering', 'Measuring', 'Iteration']),
  A('shadow-trace', 'Shadow tracing', '🌞', 'stem', [3, 10], 30, 'outside', 'calm', 0, 'dry',
    ['Chalk', 'A toy or a friend'],
    ['On a sunny morning, trace a toy\'s shadow with chalk.', 'Come back at lunch and trace it again.', 'Why did it move? Try again late afternoon.'],
    ['Earth & sun', 'Observation', 'Time']),
  A('cardboard-build', 'Cardboard box city', '📦', 'stem', [3, 12], 90, 'home', 'calm', 1, 'any',
    ['Cardboard boxes', 'Tape', 'Markers', 'Scissors (grown-up help)'],
    ['Decide what to build: a city, castle, rocket or shop.', 'Plan on paper first — older kids draw a blueprint.', 'Build, decorate and play in it all afternoon.'],
    ['Design thinking', 'Spatial skills', 'Teamwork']),
  A('ramp-race', 'Ramp racing lab', '🏎️', 'stem', [3, 9], 30, 'home', 'active', 0, 'any',
    ['Board or big book', 'Toy cars or balls', 'Books to prop'],
    ['Make a ramp; race two cars.', 'Make the ramp steeper. Predict: faster or slower?', 'Try different surfaces: towel, foil, carpet.'],
    ['Physics', 'Prediction', 'Comparing']),
  A('library-quest', 'Library adventure', '📚', 'stem', [1, 12], 60, 'out', 'calm', 0, 'any',
    ['Library card (free!)', 'Tote bag'],
    ['Each person picks one book about something they\'ve never learned about.', 'Check for free story-times or events on the notice board.', 'At home, share one fact you learned at dinner.'],
    ['Literacy', 'Curiosity', 'Community'], 'Find libraries near you in the Near Me tab.'),
  A('museum-mission', 'Museum mission cards', '🏛️', 'stem', [4, 12], 120, 'out', 'calm', 0, 'any',
    ['Index cards with missions written on them'],
    ['Before you go, write 5 missions: "find something older than grandma", "find a blue animal".', 'Kids lead the way to complete each mission.', 'Pick a favourite object and draw it on the card.'],
    ['Curiosity', 'History', 'Focus'], 'Many museums have a free-entry day — check their website.'),

  // ---------- Art ----------
  A('nature-paint', 'Paint with nature brushes', '🖌️', 'art', [2, 8], 30, 'outside', 'calm', 2, 'dry',
    ['Paper', 'Washable paint', 'Sticks, leaves, pine needles, feathers'],
    ['Collect "brushes" from the garden or park.', 'Tie them to sticks with string or a rubber band.', 'Paint and compare the marks each brush makes.'],
    ['Creativity', 'Fine motor', 'Experimenting']),
  A('chalk-mural', 'Sidewalk chalk mural', '🖍️', 'art', [2, 12], 45, 'outside', 'active', 1, 'dry',
    ['Sidewalk chalk', 'Water spray (optional)'],
    ['Pick a theme: under the sea, space, our street.', 'Draw a giant picture together.', 'Spray with water for bright colours, photograph it for your memories.'],
    ['Collaboration', 'Gross motor', 'Imagination']),
  A('puppet-show', 'Sock puppet show', '🧦', 'art', [3, 10], 60, 'home', 'calm', 1, 'any',
    ['Old socks', 'Buttons, yarn, glue, markers', 'A table + sheet for a stage'],
    ['Make one puppet per person.', 'Invent a story with a problem and a solution.', 'Perform for the family (or the stuffed animals).'],
    ['Storytelling', 'Confidence', 'Empathy']),
  A('collage', 'Magazine & scrap collage', '✂️', 'art', [3, 12], 40, 'home', 'calm', 1, 'any',
    ['Old magazines/flyers', 'Kid-safe scissors', 'Glue stick', 'Paper'],
    ['Pick a theme: "my dream day", "things that are blue".', 'Cut or tear pictures out.', 'Arrange, glue, and tell the story of the collage.'],
    ['Scissor skills', 'Self-expression']),
  A('salt-paint', 'Salt painting', '🧂', 'art', [3, 9], 30, 'home', 'calm', 1, 'any',
    ['Card', 'PVA glue', 'Salt', 'Watercolours'],
    ['Draw a picture in glue.', 'Cover with salt and shake off the extra.', 'Touch a wet watercolour brush to the salt and watch colour travel.'],
    ['Science + art', 'Fine motor']),
  A('family-portrait', 'Draw-each-other portraits', '🖼️', 'art', [3, 12], 25, 'home', 'calm', 0, 'any',
    ['Paper', 'Pencils & crayons'],
    ['Sit facing a partner.', 'Draw each other in 5 minutes — no peeking at your page for 1 minute (blind contour)!', 'Swap and laugh. Date them and keep in your memories.'],
    ['Observation', 'Connection', 'Humour']),

  // ---------- Movement ----------
  A('obstacle', 'Living-room obstacle course', '🛋️', 'movement', [2, 10], 30, 'home', 'active', 0, 'wet',
    ['Cushions, chairs, blankets, tape'],
    ['Build a course: crawl under, hop over, balance along tape.', 'Time each run — beat your own time, not each other\'s.', 'Kids redesign it for the next round.'],
    ['Gross motor', 'Planning', 'Resilience']),
  A('dance-freeze', 'Freeze dance party', '💃', 'movement', [2, 10], 15, 'home', 'active', 0, 'any',
    ['Music (any speaker)'],
    ['Dance when the music plays.', 'Freeze like a statue when it stops.', 'Add rules: freeze as an animal, freeze on one leg.'],
    ['Self-regulation', 'Listening', 'Fitness']),
  A('bike-ride', 'Family bike or scooter loop', '🚲', 'movement', [3, 12], 60, 'outside', 'active', 0, 'dry',
    ['Bikes/scooters', 'Helmets', 'Water'],
    ['Pick a safe loop or a park path.', 'Kids choose the turn at each corner (within limits).', 'Stop halfway for a snack and a "best thing so far" chat.'],
    ['Balance', 'Road safety', 'Navigation'], 'Helmets on, every time.'),
  A('animal-yoga', 'Animal yoga', '🧘', 'movement', [2, 9], 15, 'home', 'calm', 0, 'any',
    ['A soft floor or mat'],
    ['Do cat, dog, cobra, flamingo and frog poses.', 'Make the animal sound in each pose.', 'Finish lying still as a "sleeping lion" for 1 minute.'],
    ['Body awareness', 'Calming down', 'Balance']),
  A('hopscotch', 'Classic street games', '🔢', 'movement', [4, 12], 40, 'outside', 'active', 0, 'dry',
    ['Chalk', 'A pebble or beanbag'],
    ['Draw a hopscotch grid.', 'Teach a game from your own childhood: hopscotch, red-light-green-light, tag.', 'Kids invent a brand-new rule.'],
    ['Counting', 'Balance', 'Turn-taking'], 'A lovely "throwback" — share the games you played.'),
  A('balloon-keep', 'Keep the balloon up', '🎈', 'movement', [2, 8], 15, 'home', 'active', 0, 'wet',
    ['A balloon'],
    ['Keep the balloon off the floor together.', 'Count your team\'s best streak.', 'Variations: only elbows, only heads, one hand behind your back.'],
    ['Coordination', 'Teamwork'], 'Pop and bin burst balloons straight away — they are a choking risk.'),
  A('hike', 'Mini-hike with a mission', '🥾', 'movement', [3, 12], 120, 'out', 'active', 0, 'dry',
    ['Water, snacks', 'Sturdy shoes', 'Small bag'],
    ['Choose an easy trail (check Near Me → Nature & trails).', 'Give the hike a mission: find a waterfall, count bridges, spot 5 birds.', 'Let kids set the pace and pick the snack spot.'],
    ['Endurance', 'Navigation', 'Nature connection'], 'Tell someone your route; carry more water than you think.'),
  A('playground-games', 'Playground challenge cards', '🛝', 'movement', [3, 10], 60, 'out', 'active', 0, 'dry',
    ['Nothing — or a stopwatch'],
    ['Go to a playground (see Near Me).', 'Set challenges: climb without using hands on the ramp, slide backwards, count swings.', 'Kids invent challenges for the grown-ups.'],
    ['Gross motor', 'Confidence', 'Risk-assessment']),

  // ---------- Together / connection & traditions ----------
  A('blanket-fort', 'Blanket fort story night', '🏕️', 'together', [2, 12], 60, 'home', 'calm', 0, 'wet',
    ['Blankets, chairs, pegs', 'Torch', 'Books'],
    ['Build a fort together.', 'Bring in snacks, torch and books.', 'Take turns telling a story — each person adds one sentence.'],
    ['Teamwork', 'Storytelling', 'Connection']),
  A('pancake-sunday', 'Pancake tradition morning', '🥞', 'together', [2, 12], 45, 'home', 'calm', 1, 'any',
    ['Pancake ingredients', 'Toppings'],
    ['Kids measure and whisk.', 'Each person designs their own topping creation.', 'At the table, everyone shares a "rose and thorn" from the week.'],
    ['Tradition', 'Measuring', 'Talking about feelings']),
  A('time-capsule', 'Family time capsule', '📮', 'together', [4, 12], 45, 'home', 'calm', 0, 'any',
    ['Box or jar', 'Paper', 'Small keepsakes'],
    ['Each person writes or draws: my favourite food, my best friend, what I want to be.', 'Add a photo, a drawing, a toy you can part with.', 'Seal it and write an "open on" date one year from today.'],
    ['Reflection', 'Writing', 'Memory making'], 'Add the open date to your Long-term plan.'),
  A('gratitude-jar', 'Gratitude jar', '🫙', 'together', [3, 12], 10, 'home', 'calm', 0, 'any',
    ['A jar', 'Scrap paper'],
    ['Each evening, everyone writes or says one thing they\'re thankful for.', 'Fold it into the jar.', 'Read them all together at the end of the month.'],
    ['Gratitude', 'Routine', 'Writing']),
  A('picnic', 'Pack-your-own picnic', '🧺', 'together', [2, 12], 90, 'out', 'calm', 0, 'dry',
    ['Blanket', 'Food kids helped make', 'Ball or frisbee'],
    ['Kids help make sandwiches and pack.', 'Head to a park or picnic site from Near Me.', 'Play a game, then lie back and share a story.'],
    ['Planning', 'Connection', 'Outdoor time']),
  A('kindness-mission', 'Secret kindness mission', '💌', 'together', [3, 12], 30, 'home', 'calm', 0, 'any',
    ['Paper, crayons'],
    ['Pick someone: a neighbour, the mail carrier, a teacher.', 'Make a card or drawing for them.', 'Deliver it secretly (with a grown-up).'],
    ['Empathy', 'Kindness', 'Community']),
  A('baby-photos', 'When you were little', '👶', 'together', [3, 12], 20, 'home', 'calm', 0, 'any',
    ['Old printed photos'],
    ['Look through photos from when your kids — and you — were small.', 'Tell the story behind each one.', 'Kids ask one question they\'ve always wondered about.'],
    ['Identity', 'Family history', 'Connection']),
  A('board-game', 'Board-game café night', '🎲', 'together', [3, 12], 60, 'home', 'calm', 0, 'wet',
    ['Board games or cards'],
    ['Kids "run the café": make a menu and take snack orders.', 'Play 2–3 games, kids pick first.', 'Grown-ups model losing gracefully!'],
    ['Turn-taking', 'Strategy', 'Emotional regulation']),
  A('local-farm', 'Visit a farm or market', '🍓', 'together', [2, 12], 120, 'out', 'active', 0, 'dry',
    ['Reusable bags', 'Small cash'],
    ['Find a farm, orchard or farmers market nearby.', 'Kids pick one new fruit or veg to try.', 'Ask a farmer one question about how it grows.'],
    ['Healthy eating', 'Community', 'Curiosity']),
  A('zoo-day', 'Zoo or aquarium explorer day', '🦒', 'together', [1, 12], 180, 'out', 'active', 0, 'any',
    ['Water, snacks', 'Mission list'],
    ['Each child picks one animal to "research" on the day.', 'Find it, watch for 5 full minutes, notice 3 things.', 'At home, draw it and add to memories.'],
    ['Biology', 'Patience', 'Wonder']),
];

// ---------- Seasons ----------

export const SEASONS = {
  spring: { label: 'Spring', emoji: '🌷', months: [2, 3, 4] },
  summer: { label: 'Summer', emoji: '☀️', months: [5, 6, 7] },
  autumn: { label: 'Autumn', emoji: '🍁', months: [8, 9, 10] },
  winter: { label: 'Winter', emoji: '❄️', months: [11, 0, 1] },
};
